name: Checkin Test

on:
  push:
    branches:
      - master

env:
  BAZEL_OPTIMIZATION: --copt=-msse4.2 --copt=-mavx --compilation_mode=opt

jobs:

  macos:
    name: macOS ${{ matrix.python }} + ${{ matrix.version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: |
          set -x -e
          python -m pip install -U wheel setuptools
          python --version
      - name: Setup macOS
        run: |
          set -x -e
      - name: Test macOS
        run: |
          set -x -e
          python --version
          df -h
          echo ${{ matrix.version }} | awk -F: '{print $1}' | xargs python -m pip install -U
          echo ${{ matrix.version }} | awk -F: '{print $2}' | xargs python -m pip install --no-deps -U

  linux:
    name: Linux ${{ matrix.python }} + ${{ matrix.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Setup Linux
      - name: Test Linux
        run: |
          set -x -e
          python --version
          df -h

  windows:
    name: Windows ${{ matrix.python }} + ${{ matrix.version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: Setup Windows
        shell: cmd
      - name: Test Windows
        shell: cmd
        run: |
          @echo on
          python --version